// 糯糯战记 英雄数据（原创设定，美术来自 CC0 素材 0x72 DungeonTileset II）
// attack: melee 近战挥砍 / claw 徒手 / bow 弓箭 / magic 法球 / throw 投掷
// range、speed 用游戏内像素单位；aspd = 每秒攻击次数
// skill.power 是图鉴里估算综合战力用的技能分，不参与战斗计算
window.HEROES = [
  // ---------- T0 ----------
  { id: 'gorsa', name: '戈尔萨', title: '熔狱魔王', tier: 'T0', role: '重装近战',
    sprite: 'big_demon', attack: 'claw',
    hp: 2400, atk: 120, aspd: 0.8, range: 40, speed: 30,
    skill: { name: '熔岩践踏', cd: 18, power: 400, desc: '重踏地面，对前方大范围敌人造成 300 点伤害，并点燃 4 秒。' },
    lore: '从地底熔炉爬出来的魔王，走过的地方会留下焦黑的脚印。' },
  { id: 'aria', name: '艾莉娅', title: '圣裁天使', tier: 'T0', role: '远程辅助',
    sprite: 'angel', attack: 'magic', bolt: '#ffe9a8',
    hp: 900, atk: 70, aspd: 1.2, range: 220, speed: 45,
    skill: { name: '圣域庇护', cd: 25, power: 420, desc: '为全体友军施加 400 点护盾，并回复 20% 生命。' },
    lore: '个子最小的天使，翅膀一扇，整条战线都能多撑几秒。' },

  // ---------- T0.5 ----------
  { id: 'uruk', name: '乌鲁克', title: '碎岩酋长', tier: 'T0.5', role: '控制坦克',
    sprite: 'ogre', weapon: 'big_hammer', attack: 'melee', hand: [23, 26],
    hp: 2000, atk: 140, aspd: 0.6, range: 45, speed: 28,
    skill: { name: '震地重锤', cd: 16, power: 330, desc: '抡锤砸地，击飞前方敌人并眩晕 2 秒。' },
    lore: '部落里没人敢问锤子有多重。' },
  { id: 'mordred', name: '摩尔德', title: '亡灵君主', tier: 'T0.5', role: '召唤法师',
    sprite: 'necromancer', weapon: 'red_magic_staff', sheet: 'evil_wizard_2', attack: 'magic', bolt: '#c86bff',
    hp: 850, atk: 60, aspd: 1.0, range: 200, speed: 35,
    skill: { name: '白骨大军', cd: 22, power: 380, desc: '在身前召唤 6 名骷髅战士，持续 15 秒。' },
    lore: '兜帽下面什么都没有，只有法杖顶上那团烧不完的紫焰。' },
  { id: 'olin', name: '奥林', title: '翠风大法师', tier: 'T0.5', role: '范围法师',
    sprite: 'wizzard_m', weapon: 'green_magic_staff', sheet: 'wizard_pack', attack: 'magic', bolt: '#7dd8ff',
    hp: 800, atk: 95, aspd: 0.8, range: 240, speed: 38,
    skill: { name: '风暴之眼', cd: 20, power: 320, desc: '召唤龙卷风向前推进，把敌人卷回后方并造成持续伤害。' },
    lore: '一手法杖一手魔典，胡子是他的避雷针，也是他的骄傲。' },

  // ---------- T1 ----------
  { id: 'lein', name: '莱恩', title: '狮心王', tier: 'T1', role: '突进近战',
    sprite: 'knight_m', weapon: 'knight_sword', sheet: 'king_2', attack: 'melee',
    hp: 1500, atk: 90, aspd: 1.0, range: 40, speed: 42,
    skill: { name: '圣光冲锋', cd: 14, power: 260, desc: '向前冲锋 200 距离，撞开沿途敌人。' },
    lore: '亲自上前线的国王，蓝色披风是全军冲锋的信号。' },
  { id: 'sylvie', name: '希尔薇', title: '风语游侠', tier: 'T1', role: '远程输出',
    sprite: 'elf_f', weapon: 'bow', attack: 'bow',
    hp: 700, atk: 75, aspd: 1.4, range: 260, speed: 48,
    skill: { name: '穿云箭', cd: 12, power: 230, desc: '射出一支贯穿整条战线的箭，对路径上所有敌人造成 180 点伤害。' },
    lore: '射程最远的英雄，前提是有人替她挡住。' },
  { id: 'serene', name: '赛伦', title: '焰之术士', tier: 'T1', role: '范围法师',
    sprite: 'wizzard_f', weapon: 'red_magic_staff', sheet: 'evil_wizard', attack: 'magic', bolt: '#ff8a3d',
    hp: 720, atk: 85, aspd: 0.9, range: 230, speed: 38,
    skill: { name: '烈焰风暴', cd: 18, power: 250, desc: '在目标区域降下火雨，持续 5 秒灼烧敌人。' },
    lore: '奥林的师弟，手心常年托着一团火，两人从来不在同一片战场。' },
  { id: 'golem', name: '腐尸巨像', title: '墓园守门人', tier: 'T1', role: '肉盾',
    sprite: 'big_zombie', attack: 'claw',
    hp: 2200, atk: 70, aspd: 0.7, range: 40, speed: 25,
    skill: { name: '吞噬', cd: 20, power: 220, desc: '吞掉一名敌方小兵，回复自身 25% 生命。' },
    lore: '慢，硬，饿。' },

  // ---------- T2 ----------
  { id: 'brown', name: '布朗', title: '铁须战士', tier: 'T2', role: '近战输出',
    sprite: 'dwarf_m', weapon: 'double_axe', attack: 'melee',
    hp: 1300, atk: 85, aspd: 0.9, range: 38, speed: 34,
    skill: { name: '旋风斧', cd: 15, power: 200, desc: '原地旋转 3 秒，持续伤害周围敌人。' },
    lore: '矮人里个子最高的，所以总被派去打头阵。' },
  { id: 'freya', name: '芙蕾雅', title: '女武神', tier: 'T2', role: '中距近战',
    sprite: 'knight_f', weapon: 'spear', attack: 'melee',
    hp: 1250, atk: 80, aspd: 0.9, range: 60, speed: 40,
    skill: { name: '天降之矛', cd: 16, power: 190, desc: '投出长矛钉住第一个敌人，造成 220 点伤害并定身 1.5 秒。' },
    lore: '长矛比别人的剑多出一截，这一截就是先手。' },
  { id: 'grey', name: '格雷', title: '瘟疫医生', tier: 'T2', role: '持续伤害',
    sprite: 'doc', weapon: 'knife', attack: 'throw', bolt: '#9be35a',
    hp: 750, atk: 55, aspd: 1.1, range: 170, speed: 36,
    skill: { name: '瘟疫毒雾', cd: 17, power: 190, desc: '投掷毒瓶，形成 6 秒毒雾，敌人在其中每秒损失 3% 生命。' },
    lore: '他说自己是来治病的。' },
  { id: 'karg', name: '卡格', title: '血斧督军', tier: 'T2', role: '团队增益',
    sprite: 'orc_warrior', weapon: 'waraxe', attack: 'melee',
    hp: 1400, atk: 80, aspd: 0.85, range: 40, speed: 36,
    skill: { name: '战争怒吼', cd: 24, power: 180, desc: '全体友军攻击速度提升 30%，持续 8 秒。' },
    lore: '嗓门比斧子更有用。' },
  { id: 'zass', name: '札斯', title: '赤巾浪人', tier: 'T2', role: '切后排',
    sprite: 'lizard_m', weapon: 'katana', sheet: 'martial_hero', attack: 'melee',
    hp: 900, atk: 110, aspd: 1.1, range: 35, speed: 60,
    skill: { name: '影袭', cd: 14, power: 180, desc: '潜入阴影，瞬移到敌方最后排的远程单位身后并造成 2 倍伤害。' },
    lore: '斗笠压得很低，红头巾是他出刀前唯一能看见的东西。' },

  // ---------- T3 ----------
  { id: 'jack', name: '杰克', title: '南瓜头', tier: 'T3', role: '近战',
    sprite: 'pumpkin_dude', weapon: 'machete', attack: 'melee',
    hp: 1000, atk: 70, aspd: 0.9, range: 40, speed: 38,
    skill: { name: '南瓜炸弹', cd: 18, power: 150, desc: '扔出一颗会爆炸的南瓜，造成 160 点范围伤害。' },
    lore: '每年秋天都会换一个新脑袋。' },
  { id: 'gip', name: '吉普', title: '地精飞斧手', tier: 'T3', role: '远程输出',
    sprite: 'goblin', weapon: 'throwing_axe', attack: 'throw', hand: [11, 12],
    hp: 550, atk: 60, aspd: 1.0, range: 180, speed: 46,
    skill: { name: '连环飞斧', cd: 12, power: 140, desc: '连续扔出 3 把飞斧，每把造成 70 点伤害。' },
    lore: '斧子扔完了就去捡，所以跑得很快。' },
  { id: 'mura', name: '穆拉', title: '兽人萨满', tier: 'T3', role: '治疗',
    sprite: 'orc_shaman', weapon: 'green_magic_staff', attack: 'magic', bolt: '#5fe0c4',
    hp: 700, atk: 45, aspd: 1.0, range: 200, speed: 34,
    skill: { name: '治疗图腾', cd: 20, power: 160, desc: '插下图腾，8 秒内每秒为附近友军回复 40 生命。' },
    lore: '部落里唯一会包扎的人。' },
  { id: 'bones', name: '骸骨射手', title: '无名弓兵', tier: 'T3', role: '远程输出',
    sprite: 'skelet', weapon: 'bow_2', attack: 'bow', hand: [11, 12],
    hp: 500, atk: 55, aspd: 1.2, range: 240, speed: 40,
    skill: { name: '骨箭齐射', cd: 14, power: 130, desc: '向前方区域射出 5 支箭，每支造成 50 点伤害。' },
    lore: '射得不准，但从来不累。' },
  { id: 'pupu', name: '噗噗', title: '炎魔小鬼', tier: 'T3', role: '远程法师',
    sprite: 'imp', attack: 'magic', bolt: '#ff5a3d',
    hp: 480, atk: 50, aspd: 1.2, range: 190, speed: 44,
    skill: { name: '自燃冲撞', cd: 16, power: 130, desc: '点燃自己冲进敌群，造成 150 点范围伤害，自身损失 20% 生命。' },
    lore: '戈尔萨脚边捡来的小东西。' },
  { id: 'helga', name: '赫尔佳', title: '熔炉之女', tier: 'T3', role: '守护',
    sprite: 'dwarf_f', weapon: 'hammer', attack: 'melee',
    hp: 1100, atk: 65, aspd: 0.8, range: 40, speed: 32,
    skill: { name: '加固水晶', cd: 30, power: 140, desc: '为己方水晶回复 8% 生命，并在 6 秒内减少水晶受到的伤害 50%。' },
    lore: '布朗的妹妹，锤子是自己打的。' },
];

// 综合战力估算：sqrt(生命 × 每秒伤害) × (1 + 射程/400) + 技能分
window.heroPower = function (h) {
  return Math.round(Math.sqrt(h.hp * h.atk * h.aspd) * (1 + h.range / 400) + h.skill.power);
};
